### PR TITLE
fb_metoffice; updated SMC grid generation for command line usage

### PR DESCRIPTION
**Pull request by ukmo-ansaulter**
This update to gridgen is a first step in enabling the code to be run by users without the need to set up grid specific python run scripts locally. Key changes are as follows:

- gebco_reduce, gridgen and smc_test functions are now run using dedicated run_scripts and user defined configuration files
- a worked_examples directory has been added which takes users through the steps needed to generate and test example grids; the code has been tested at Met Office to create all of these examples using the described methods
- preliminary templates for code license and version history have been added to modules relevant to the worked examples

Tests so far have been for global SMC grids; regular and regional SMC grids will be tested in subsequent issues/PRs

### CODE REVIEW

**Comment by ukmo-ansaulter** [comment]
Hi Tom, Chris, Jian-Guo,

I've created this PR with all of you as reviewers, but hopefully you can each just check a couple of specific things and it won't be too onerous.

Tom - the main thing for you to check you are OK with is the license, contributors list and how I've suggested applying this within code modules; I'll also send you a separate email regarding how Met Office would prefer this to be 'gate-kept'

Chris - can you just check that where I have python libraries and scripts in reduce_gebco, gridgen and smc_test directories, these are halfway sensible laid out and if any other python files (the __ones__) need adding to make this work well

Jian-Guo - I have tried to generalise the fortran code and run scripts for cell face generation and propagation testing, plus have amalgamated your grid plotting functions into a single library. Can you check that you are happy with what has been done so far (the fortran needs further tidying up) and also that you are OK with the way I am attributing you in the code version histories?

Thanks all
Andy

**Comment by ukmo-ansaulter** [comment]
> Just went through the changes and they look fine. Need to see the full files and some examples before the approval. Jian-Guo 06May2020

Thanks @ukmo-jianguo-li 
I've set out a few grid generation and testing examples in the worked_examples directory of this branch
You can also look at the config, data files and results locally at the Met Office in the following directories under /project/ofrd/waves/wavegrids/global
GS256A
GS256L2
GS512L3A
GS512L5A
for each of the model subdirectories, the propagation test results and plots are stored in the subdirectory smcProps

**Comment by ukmo-ansaulter** [comment]
Outcomes from code review meeting with @ukmo-jianguo-li and @ukmo-ccbunney 

1. Corrections and re-testing needed for arctic cell headers (gridgen) and pole values (propSMC); reviewer: @ukmo-jianguo-li 
2. Remove Version statement from licence/revision headers, look into add a change log
3. python code clean-up based on feedback from @ukmo-ccbunney 

Further code developments are noted and have been raised as issues: #5 , #6 , #7 , #8

**Comment by ukmo-ansaulter** [comment]
@ukmo-jianguo-li I have corrected the problem with boundary cell numbers and the arctic reference direction in the propagation test. The new code has been run on the following configurations:
- GS256A
-GS512L3A

Please can you confirm you are happy with these two test cases now? Also, as a final check, please confirm the order of the cell numbers in the header of the arcCels.dat file - should this be 1) number of cells in file; 2) number of cells in top two rows of global grid; 3 number of cells in bottom two rows of arctic grid?

Thanks! Andy

**Comment by ukmo-ansaulter** [comment]
@ukmo-ccbunney I've followed through the suggestions from your review:

- A CHANGELOG.rst file has been added and version numbers removed from individual code headers
- Makefiles have been added for genSides and smcProps
- all python code developed in this branch has been checked and updated to use triple double quotes for doc strings and empty returns have been removed
- I pulled in your suggested changes to gebco_reduce.py and also updated loops to use ix,iy convention; I have tested these by successfully generating a new regular grid from GEBCO 2019

One note is that I have not extended the review of variable naming and use of loops to other python code in this branch just yet. These are due to be reviewed and modified in the branch for issue #3 

Many thanks! Andy

**Comment by ukmo-jianguo-li** [comment]
@ukmo-ansaulter  Hi, Andy.  I have viewed your new tests and they look fine now.  Some strange propagation patterns new Cap Verde islands might be caused by strong refraction but may ignore them for now.  Happy to close the review pull unless you have other issues for me to check.
Kind regards. 
Jian-Guo

**Pull request merged**
